version: '3.8'

services:
  php-apache:
    build: .
    container_name: mini-erp-php
    ports:
      - "8080:80" # Mapeia a porta 8080 do host para a porta 80 do container
    volumes:
      - .:/var/www/html # Sincroniza o código local com o container
    networks:
      - mini-erp-network

  mysql:
    image: mysql:5.7
    container_name: mini-erp-mysql
    ports:
      - "3306:3306" # Porta padrão do MySQL
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mini_erp
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    networks:
      - mini-erp-network

volumes:
  db_data:

networks:
  mini-erp-network:
    driver: bridge